sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - secure: "oGkyVJXQNZjbBav/SH3tCMQI2iE7xp+sGPntbv0RETkxDohW5oDpMlWfjI+6YS7AN2LmMbvkSowpU5y9nvU3vu0ICaOy/4z7My6k/3uabVklEgd7lVWkf/pW1EAIGx+jCKqP2lnR7XgpT/xenD2JzNpYHPm6EywQ6RBUv9VXvfvQQy9LFmEsZ74/ayJ3NGIh99Br69ji1HhPixxIn6g7fB7ykOj8BXjHihbf0ntzc1DQlVJ1EJro+TXa0/CWxHRnfEyirdj8dQHxM02pkVJGV31Dy3IC3iaX9g5m3uWAU7niRhCk5FwFmDZZl4lxbYtd5NywNfVL2fbRDLodjiyj2bzNDV6mibV0ch5ntgCXJK7j904/GjBWrLk5tancjYk4lkurDP2n7vxoi/fuNoS3E3iaoo6JZaSF+noyb063o994oZggCsMfxK+xqiVQNstgifGAZ4KsQYyCNKwTsWdTlvUqVF377tSY57IpTmSTEMO6B2jokY/Er+hnmaYgZxs4CNSF/cAcOE0a+HYJJCHw2V60CY77Er13PYyY/JEEuicI21MTxr0wYGV0VlpUrUlCz1XdKU5fDEDZNX7IGHRAwdeQhFbu+/qOD+0aX+HkRwlifS04m1J3QFf/xB4cBXS7N9f8eyy9nlpG+dAVGNbvdsaTeHeEnngvgbJY6yFk0LY=" # DOCKER_EMAIL
    - secure: "cSba1BKAHZjas7/kHCfCOW0is2GRspaBK7heBO42rr/5xAQ/A4Pb6esJ2yZo92LvcAnKjMEu8WyJvG3BdBf8/eIS8eSwewzjk+1Whfjcfn4BQH5ypiZCaMSmiIVOKcKaUVefrcEWhK46IvBay3gnshNE8eYzk800VCrppEz16YVyYvBCRni0+C11EQlvhzNTbm/+WtRlhOmgCUIhTQHGMpTBP3/gq3UWyzweyAbNpfj0V5PR4/Bc6tx5ZQXbBBvxiijK7uGQO+p1PPhc8gzPlY/JfzlSyowojk2ArCAhSZUz+Tq8jrCVjSj/vAySCwIdt4QSv4NOzytZbmdzUz124o+kttDUfayojXuB9IWcORiy7ZhYIOzAVV8sSJfVcOC97DzHy8mbHKq6rfGSyu+tZlmBrsM+uj+meh9ijHIUR3w1syo48snQpvf5LmZhyzC0immBSxz4b6woI88spAZwjiFaaelCTO0mZqD3eyC/MLGyYZLELQqPX9foqm27bfRDAgnSQ9DT/Dom9DzNiCU+1QgO0m3h/C2X/En9nEolF526CNAv6/htcjITGdpVa4cxloHT33Uzk2IoVY+nv5973KF0DyDospu20kT1BIX91gY7m4au4ubgAuUBMGOERY38L5X4IrTLS/94ICRgCe/zcjwHnt/wk7Bpxzf1SyB+GXc=" # DOCKER_USER
    - secure: "pN5ulbomx5jGb3GDAsvAcOD+wEdR4H8SNwTSj6Q6TQJb0SA9rutQ3hJu55wSZpR05uNsiEvRM6fvXwxVH5Jes0rPtFBoa3LWGMd5R0W2hxRBtus0DEALrww7rwKV0tzY6wJsJnv0fdSWbh3dJdYKXoRgpC5QODN0bRzSjDQmsRglJHYr5GzB/JIYqf5zDQVGEmcIgm7nSCjIUtPjZCtlpXGffyIVvyGMinVu0FfC3oKpDfXiODq/cePihVK5oOC+OWHi6ydIy5EMr7eQqOezQOUNhzwis3xEgChTIOTWTB1K0+4fC2ojePClJj0BGZPP9r22DqhJca1WjnUFRvk41kF8vW5hWMczclDtrKFBhhIvF+QKvK/x2m8XpSRKFJfKd+G1MKNlhL/8DSvzrAAkI2i5vNFVzgL3TE2sPImt5rc7sdnzR7RL19FuehKWqlzBQ4+Tp+7A3bJmAbxYfWjTLfHGg58QcJNlr60zgAxfku3Kuk99fw3X2Ty4f+BKQ9W5qyUWbKgl64DS2++8UrgNN2MJKV9YJWbndQDmIZ4PFi0ZWgNQuh/azyY0Fout22fXDLCi4Hl5GKX17qWHOFKpo75zOdGkYRDamTugRuIzGlaDItR+kdk7xfV1hegFmPLKdQxyZM7XyRHZ1Nz14BmcJQe/vWar+QntQlatIP/PfZE=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=wallacecamacho/piggymetrics-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=wallacecamacho/piggymetrics-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=wallacecamacho/piggymetrics-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # ACCOUNT SERVICE
  - export ACCOUNT_SERVICE=wallacecamacho/piggymetrics-account-service
  - docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE

  # MONITORING
  - export MONITORING=wallacecamacho/piggymetrics-monitoring
  - docker build -t $MONITORING:$COMMIT ./monitoring
  - docker tag $MONITORING:$COMMIT $MONITORING:$TAG
  - docker push $MONITORING

  # TURBINE STREAM SERVICE
  - export TURBINE=wallacecamacho/piggymetrics-turbine-stream-service
  - docker build -t $TURBINE:$COMMIT ./turbine-stream-service
  - docker tag $TURBINE:$COMMIT $TURBINE:$TAG
  - docker push $TURBINE

  # MONGO DB
  - export MONGO_DB=wallacecamacho/piggymetrics-mongodb
  - docker build -t $MONGO_DB:$COMMIT ./mongodb
  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
  - docker push $MONGO_DB
