#!/bin/sh


export CONFIG_SERVICE_PASSWORD="123"
echo CONFIG_SERVICE_PASSWORD=$CONFIG_SERVICE_PASSWORD
export NOTIFICATION_SERVICE_PASSWORD="123"
echo NOTIFICATION_SERVICE_PASSWORD=$NOTIFICATION_SERVICE_PASSWORD
export STATISTICS_SERVICE_PASSWORD="123"
echo STATISTICS_SERVICE_PASSWORD=$STATISTICS_SERVICE_PASSWORD
export ACCOUNT_SERVICE_PASSWORD="123"
echo ACCOUNT_SERVICE_PASSWORD=$ACCOUNT_SERVICE_PASSWORD
export MONGODB_PASSWORD="123"
echo MONGODB_PASSWORD=$MONGODB_PASSWORD

