spring:
  data:
    mongodb:
      host: example-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: springseed
      port: 27017

server:
  servlet:
    context-path: /example
  port: 6000

feign:
  hystrix:
    enabled: true